### ISSUE TITLE
mosser?

### ISSUE THREAD

**Issue by gingerbeardman** [tyfkda/tyfkda.github.io#1]
Hi,

Do you have a download for the "mosser" game featured in the post below?

https://tyfkda.github.io/blog/2014/11/22/generate-puzzle.html

Old location was http://www.din.or.jp/~ku_/junk/mosser11.zip but this is no longer available and is not archived?

An older version of "mosser" was at http://www.onionsoft.net/hsp/contest2004/data/hspcontest368.exe but this is also disappeared.

**Comment by tyfkda** [comment]
Hi @gingerbeardman ,

I love Mosser, it is a simple but a good game.
Unfortunately, I have lost the archive file.

I'm not sure, but it looks you can play extended version of the game called "まるぼうしかく" (Circle, Stick and Rectangle) on Nintendo Wii or Nintendo DS:
http://susami.co.jp/books/gamedesign/ (Japanese)

**Comment by gingerbeardman** [comment]
Hi. Yes I own MaBoShi, so I was interested to see the origin of its Square game (mosser). 

I have found the origin of its Circle game as an SWF file (circular) here http://web.archive.org/web/20031202202659/http://www.din.or.jp:80/~ku_/junk/junk.htm

**Comment by gingerbeardman** [comment]
I rediscovered your blog searching for Carton-kun :)

And just now I found mosser! If you follow the link on your page:

http://www.onionsoft.net/hsp/contest2004/result.html#368

you can see each game entry has a certain filename pattern

- http://www.onionsoft.net/hsp/contest2004/data/hspcontest373.exe

So we simply change it to 368 (mosser entry number)

- http://www.onionsoft.net/hsp/contest2004/data/hspcontest368.exe

Somehow the file was not there in 2019, but it is there now. Great news :)

Anyway, download is achieved :)

![Screen shot 2023-06-13 at 23 47 10](https://github.com/tyfkda/tyfkda.github.io/assets/49612/f9667282-c9ee-47aa-8e98-6553adb55c47)

(playing on macOS using CrossOver)
